### ISSUE TITLE
Add to Quote Button not working

### ISSUE THREAD

**Issue by parhamcurtis** [pinalj/quotes-for-woocommerce#22]
Hello I am using version 3.0.7. It is producing a 500 server error when adding a product to quote. It fails somewhere in the add_to_quote method inside  the class_quote.php file. It fails at this line.
do_action( 'woocommerce_add_to_cart', $cart_item_key, $product_id, $quantity, $variation_id, $variations, $cart_item_data );

near the end of the method. It seems to make it through the calculate_totals hook so I am not sure what is going on. 

Can you take a look?

https://mvplegacy.com/product/gildan-100-cotton-midweight-t-shirt/

**Comment by pinalj** [comment]
Hi @parhamcurtis,

1. I was able to replicate the issue which you have mentioned above on the link shared.
2. Are you able to add products which are not enabled for quotes fine?
3. If no, then the issue is not with the Quotes plugin. The plugin simply renames the 'Add to Cart' button to 'Request Quote', so ideally there should be no issues when adding products to the cart.
4. If yes, then can you please check by deactivating all the plugins except WooCommerce and Quotes if the issue is replicated. 
5. If not, then please activate one plugin at a time and check the conflicting plugin.

Please let me know the results.

Pinal

**Comment by parhamcurtis** [comment]
Pinal,
Thank you so much for  your plugin and for responding. I did find that another plugin was breaking this. It turns out that both plugins were using the 'woocommerce_add_to_cart' action so I add an if statement in the other plugin's function to check for $_POST['is_quote'] then skipped their code. Seems to solve the conflict kind of.
